### ISSUE TITLE
HTTP Post with json content

### ISSUE THREAD

**Issue by frhd** [basicallydan/interfake#32]
It would be nice to actually post real json data in a HTTP Post and store it temporarily. Is it feasible in interfake?

**Comment by basicallydan** [comment]
I think this should look like this:

```javascript
interfake.post('/retrieve').echo();
```

Any thoughts, @frhd?

**Comment by basicallydan** [comment]
Just added this in v1.15.0 :)

**Comment by frhd** [comment]
@basicallydan Thanks for the great work! :)

`interfake.post('/retrieve').echo();` works as expected.  Post something to `/retrieve` and it gets echoed back.

However, I'm not sure if that's exactly what I was talking about initially. The use case I had in mind was  going beyond static API tests where you know in and out data in advance, but mirroring CRUD-like API behaviour in tests. Something along the lines of:

```
// post data, e.g. "1=item1"
interfake.post('/item/new').status(201).body({ created: true });

// return previous POST data, e.g. gets {"1":"item1"}
interfake.get('/items').echo();
```

I think I will try my hand at this, since my familiarity with node has slightly been improved over the year :)
