### ISSUE TITLE
Publish 'deepmerge' dependency to npm

### ISSUE THREAD

**Issue by popeindustries** [basicallydan/interfake#42]
It is generally bad form to publish things to npm when they rely on git dependencies. These dependencies often timeout (especially with npm v3), and Interfake often ends up crashing our installs. How about using a scoped npm package instead (`@basicallydan/deepmerge`)?

**Comment by basicallydan** [comment]
I agree, good idea. Although, I have noticed a lot of activity on deepmerge
which I haven't been paying attention to, so first I'll check to see if
maybe it meets the requirements of Interfake now.

Thanks for the excellent issue Alexander!
